server:
  port: 8080
  #servlet:
  #context-path: /shop #项目名称
  tomcat:
    max-http-post-size: -1



spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    charset: utf-8 #编码方式
    check-template-location: true #检查模板位置是否存在
    content-type: text/html
    enabled: true #是否启用freemarker
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates
    settings:
      classic_compatible: true

    mvc:
      static-path-pattern: /static/**  #项目中访问静态资源的前缀名
    #resources:
    #  static-locations: classpath:/D:/img
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload/
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

#配置mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  #type-aliases-package: com.chinasoft.shop.domain
#通配符

#showSql
logging:
  level:
    com:
      example:
        mapper : debug